### ISSUE TITLE
Seize the means of production!

### ISSUE THREAD

**Issue by piotr-yuxuan** [msolli/proletarian#1]
It's great to see that you used a classless language for the proletariat, and I'm pleased to meet with `proletarian.worker` and `java.util.concurrent.ThreadFactory` in this code.
![](https://i.imgur.com/CsR4Hsk.jpeg)

**Comment by msolli** [comment]
Proletarian will indeed seize the means of production, by way of the [handle-job!](https://github.com/msolli/proletarian/blob/main/src/proletarian/job.clj#L8) multimethod. Thanks for your interest - let me know if you have any questions, ideas or issues.
