### ISSUE TITLE
Manually run jobs

### ISSUE THREAD

**Issue by retro** [msolli/proletarian#2]
Is there a way to manually run jobs in the DB? We would use it in the development and test environments, where we might need some finer control over _when_ are the jobs running.

**Comment by msolli** [comment]
First, let me understand your use case a bit more. Are you talking about integration testing, where you want to test that the job has been run and that the work in the handler has been done? Or is it that you want to specify some time in the future that the job is run? Or something else?

**Comment by retro** [comment]
In the development I would like to be able to run jobs without starting the worker process. For instance:

1. Call a domain function which queues the job
2. Manually trigger job from REPL

This way we can develop without starting the whole app in every scenario. This would also be convenient in some test scenarios where we might test domain functions without starting the whole app.

I think that the only change that might be needed is extracting this into a `defn` without marking it as a private var https://github.com/msolli/proletarian/blob/main/src/proletarian/worker.clj#L20-L41

For real integration tests, I see value in starting the worker process.

**Comment by msolli** [comment]
@retro Please have a look at PR #3 - would something like this work for your use case?

**Comment by retro** [comment]
@msolli This is great, thank you! I think it will cover all the cases I have in mind
