### ISSUE TITLE
Job handlers would ideally use a Component/Integrant component/system as an argument 

### ISSUE THREAD

**Issue by vemv** [msolli/proletarian#21]
Hi!

Thanks for the excellent lib.

I've noticed it's common for job handlers to require the Component/Integrant system to do anything useful.

(If not the entire system, it could be at least a specific component or selection of components).

e.g. a job handler will commonly need the database.

While I could save the Integrant system to a global var, that's not intended usage. It would also easily result in circular references.

I believe that a reasonable pattern/solution would be:

* wrap Proletarian in a Component
  * this Component would have most of the system - whatever the job handlers may need
* In this Component, call `proletarian.worker/create-queue-worker`
* **(the feature request)** - pass a new option e.g. `:payload-middleware` such that I can merge the system into each payload message.

This is how it would look like for consumers:

```clj
(defmethod integrant.core/init-key ::worker [_ {::keys [db mailer redis]}]
  (proletarian.worker/create-queue-worker db
                                          handle-job!
                                          {:proletarian/payload-middleware (fn [payload]
                                                                             (assoc payload
                                                                                    ::db db
                                                                                    ::mailer mailer
                                                                                    ::redis redis))})
  ,,,)
```

(that's not technically middleware - other names welcome)

WDYT?

Thanks  - V

**Comment by msolli** [comment]
Hi, thanks for reaching out!

Whenever I have a `handle-job!` function that needs more information (or _state_) than the Proletarian worker provides, I capture it from the scope where `create-queue-worker` is called:
```clojure
(defn handle-job! [{::keys [db mailer redis]} job-type payload]
  ;; handle the job...
)

(defmethod integrant.core/init-key ::worker [_ {::keys [db mailer redis]}]
  (proletarian.worker/create-queue-worker db
                                          (partial handle-job! {::db db
                                                                ::mailer mailer
                                                                ::redis redis})
                                          {#_the-options-map})
  ,,,)
```

Would this work for you?

**Comment by vemv** [comment]
That seems to make sense!

I'll give it a try - update during the week hopefully.

**Comment by vemv** [comment]
This worked nicely.

Thanks for the suggestion!
